#!/usr/bin/env python3
"""Convert a binary file to an xxd-compatible C header, without requiring xxd."""

from __future__ import annotations

import argparse
import os
import re
import tempfile
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--symbol", required=True)
    parser.add_argument("--bytes-per-line", type=int, default=12)
    return parser.parse_args()


def validate_symbol(symbol: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", symbol):
        raise ValueError(f"invalid C identifier: {symbol!r}")
    return symbol


def generate(input_path: Path, output_path: Path, symbol: str, bytes_per_line: int) -> None:
    if bytes_per_line <= 0:
        raise ValueError("--bytes-per-line must be positive")
    data = input_path.read_bytes()
    guard = f"DOOMBF_GENERATED_{symbol.upper()}_H"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=output_path.name + ".", suffix=".tmp", dir=output_path.parent)
    try:
        with os.fdopen(fd, "w", encoding="ascii", newline="\n") as stream:
            stream.write("/* Generated by tools/bin2c.py. Do not edit. */\n")
            stream.write(f"#ifndef {guard}\n#define {guard}\n\n")
            stream.write(f"unsigned char {symbol}[] = {{\n")
            for offset in range(0, len(data), bytes_per_line):
                chunk = data[offset : offset + bytes_per_line]
                values = ", ".join(f"0x{value:02x}" for value in chunk)
                suffix = "," if offset + len(chunk) < len(data) else ""
                stream.write(f"  {values}{suffix}\n")
            stream.write("};\n")
            stream.write(f"unsigned int {symbol}_len = {len(data)}u;\n\n")
            stream.write(f"#endif /* {guard} */\n")

        temporary_path = Path(temporary_name)
        if output_path.exists() and output_path.read_bytes() == temporary_path.read_bytes():
            temporary_path.unlink()
        else:
            os.replace(temporary_path, output_path)
    except BaseException:
        try:
            Path(temporary_name).unlink()
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    args = parse_args()
    symbol = validate_symbol(args.symbol)
    if not args.input.is_file():
        raise FileNotFoundError(f"input file not found: {args.input}")
    generate(args.input.resolve(), args.output.resolve(), symbol, args.bytes_per_line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
